export const currencies: {
  currency: string;
  currencyName: string;
  country: string;
}[] = [
  {
    currency: "AED",
    currencyName: "UAE Dirham",
    country: "United Arab Emirates",
  },
  { currency: "AFN", currencyName: "Afghan Afghani", country: "Afghanistan" },
  { currency: "ALL", currencyName: "Albanian Lek", country: "Albania" },
  { currency: "AMD", currencyName: "Armenian Dram", country: "Armenia" },
  {
    currency: "ANG",
    currencyName: "Netherlands Antillian Guilder",
    country: "Netherlands Antilles",
  },
  { currency: "AOA", currencyName: "Angolan Kwanza", country: "Angola" },
  { currency: "ARS", currencyName: "Argentine Peso", country: "Argentina" },
  { currency: "AUD", currencyName: "Australian Dollar", country: "Australia" },
  { currency: "AWG", currencyName: "Aruban Florin", country: "Aruba" },
  { currency: "AZN", currencyName: "Azerbaijani Manat", country: "Azerbaijan" },
  {
    currency: "BAM",
    currencyName: "Bosnia and Herzegovina Mark",
    country: "Bosnia and Herzegovina",
  },
  { currency: "BBD", currencyName: "Barbados Dollar", country: "Barbados" },
  { currency: "BDT", currencyName: "Bangladeshi Taka", country: "Bangladesh" },
  { currency: "BGN", currencyName: "Bulgarian Lev", country: "Bulgaria" },
  { currency: "BHD", currencyName: "Bahraini Dinar", country: "Bahrain" },
  { currency: "BIF", currencyName: "Burundian Franc", country: "Burundi" },
  { currency: "BMD", currencyName: "Bermudian Dollar", country: "Bermuda" },
  { currency: "BND", currencyName: "Brunei Dollar", country: "Brunei" },
  { currency: "BOB", currencyName: "Bolivian Boliviano", country: "Bolivia" },
  { currency: "BRL", currencyName: "Brazilian Real", country: "Brazil" },
  { currency: "BSD", currencyName: "Bahamian Dollar", country: "Bahamas" },
  { currency: "BTN", currencyName: "Bhutanese Ngultrum", country: "Bhutan" },
  { currency: "BWP", currencyName: "Botswana Pula", country: "Botswana" },
  { currency: "BYN", currencyName: "Belarusian Ruble", country: "Belarus" },
  { currency: "BZD", currencyName: "Belize Dollar", country: "Belize" },
  { currency: "CAD", currencyName: "Canadian Dollar", country: "Canada" },
  {
    currency: "CDF",
    currencyName: "Congolese Franc",
    country: "Democratic Republic of the Congo",
  },
  { currency: "CHF", currencyName: "Swiss Franc", country: "Switzerland" },
  { currency: "CLP", currencyName: "Chilean Peso", country: "Chile" },
  { currency: "CNY", currencyName: "Chinese Renminbi", country: "China" },
  { currency: "COP", currencyName: "Colombian Peso", country: "Colombia" },
  { currency: "CRC", currencyName: "Costa Rican Colon", country: "Costa Rica" },
  { currency: "CUP", currencyName: "Cuban Peso", country: "Cuba" },
  {
    currency: "CVE",
    currencyName: "Cape Verdean Escudo",
    country: "Cape Verde",
  },
  { currency: "CZK", currencyName: "Czech Koruna", country: "Czech Republic" },
  { currency: "DJF", currencyName: "Djiboutian Franc", country: "Djibouti" },
  { currency: "DKK", currencyName: "Danish Krone", country: "Denmark" },
  {
    currency: "DOP",
    currencyName: "Dominican Peso",
    country: "Dominican Republic",
  },
  { currency: "DZD", currencyName: "Algerian Dinar", country: "Algeria" },
  { currency: "EGP", currencyName: "Egyptian Pound", country: "Egypt" },
  { currency: "ERN", currencyName: "Eritrean Nakfa", country: "Eritrea" },
  { currency: "ETB", currencyName: "Ethiopian Birr", country: "Ethiopia" },
  { currency: "EUR", currencyName: "Euro", country: "European Union" },
  { currency: "FJD", currencyName: "Fiji Dollar", country: "Fiji" },
  {
    currency: "FKP",
    currencyName: "Falkland Islands Pound",
    country: "Falkland Islands",
  },
  { currency: "FOK", currencyName: "Faroese Króna", country: "Faroe Islands" },
  {
    currency: "GBP",
    currencyName: "Pound Sterling",
    country: "United Kingdom",
  },
  { currency: "GEL", currencyName: "Georgian Lari", country: "Georgia" },
  { currency: "GGP", currencyName: "Guernsey Pound", country: "Guernsey" },
  { currency: "GHS", currencyName: "Ghanaian Cedi", country: "Ghana" },
  { currency: "GIP", currencyName: "Gibraltar Pound", country: "Gibraltar" },
  { currency: "GMD", currencyName: "Gambian Dalasi", country: "The Gambia" },
  { currency: "GNF", currencyName: "Guinean Franc", country: "Guinea" },
  { currency: "GTQ", currencyName: "Guatemalan Quetzal", country: "Guatemala" },
  { currency: "GYD", currencyName: "Guyanese Dollar", country: "Guyana" },
  { currency: "HKD", currencyName: "Hong Kong Dollar", country: "Hong Kong" },
  { currency: "HNL", currencyName: "Honduran Lempira", country: "Honduras" },
  { currency: "HRK", currencyName: "Croatian Kuna", country: "Croatia" },
  { currency: "HTG", currencyName: "Haitian Gourde", country: "Haiti" },
  { currency: "HUF", currencyName: "Hungarian Forint", country: "Hungary" },
  { currency: "IDR", currencyName: "Indonesian Rupiah", country: "Indonesia" },
  { currency: "ILS", currencyName: "Israeli New Shekel", country: "Israel" },
  { currency: "IMP", currencyName: "Manx Pound", country: "Isle of Man" },
  { currency: "INR", currencyName: "Indian Rupee", country: "India" },
  { currency: "IQD", currencyName: "Iraqi Dinar", country: "Iraq" },
  { currency: "IRR", currencyName: "Iranian Rial", country: "Iran" },
  { currency: "ISK", currencyName: "Icelandic Króna", country: "Iceland" },
  { currency: "JEP", currencyName: "Jersey Pound", country: "Jersey" },
  { currency: "JMD", currencyName: "Jamaican Dollar", country: "Jamaica" },
  { currency: "JOD", currencyName: "Jordanian Dinar", country: "Jordan" },
  { currency: "JPY", currencyName: "Japanese Yen", country: "Japan" },
  { currency: "KES", currencyName: "Kenyan Shilling", country: "Kenya" },
  { currency: "KGS", currencyName: "Kyrgyzstani Som", country: "Kyrgyzstan" },
  { currency: "KHR", currencyName: "Cambodian Riel", country: "Cambodia" },
  { currency: "KID", currencyName: "Kiribati Dollar", country: "Kiribati" },
  { currency: "KMF", currencyName: "Comorian Franc", country: "Comoros" },
  { currency: "KRW", currencyName: "South Korean Won", country: "South Korea" },
  { currency: "KWD", currencyName: "Kuwaiti Dinar", country: "Kuwait" },
  {
    currency: "KYD",
    currencyName: "Cayman Islands Dollar",
    country: "Cayman Islands",
  },
  { currency: "KZT", currencyName: "Kazakhstani Tenge", country: "Kazakhstan" },
  { currency: "LAK", currencyName: "Lao Kip", country: "Laos" },
  { currency: "LBP", currencyName: "Lebanese Pound", country: "Lebanon" },
  { currency: "LKR", currencyName: "Sri Lanka Rupee", country: "Sri Lanka" },
  { currency: "LRD", currencyName: "Liberian Dollar", country: "Liberia" },
  { currency: "LSL", currencyName: "Lesotho Loti", country: "Lesotho" },
  { currency: "LYD", currencyName: "Libyan Dinar", country: "Libya" },
  { currency: "MAD", currencyName: "Moroccan Dirham", country: "Morocco" },
  { currency: "MDL", currencyName: "Moldovan Leu", country: "Moldova" },
  { currency: "MGA", currencyName: "Malagasy Ariary", country: "Madagascar" },
  {
    currency: "MKD",
    currencyName: "Macedonian Denar",
    country: "North Macedonia",
  },
  { currency: "MMK", currencyName: "Burmese Kyat", country: "Myanmar" },
  { currency: "MNT", currencyName: "Mongolian Tögrög", country: "Mongolia" },
  { currency: "MOP", currencyName: "Macanese Pataca", country: "Macau" },
  {
    currency: "MRU",
    currencyName: "Mauritanian Ouguiya",
    country: "Mauritania",
  },
  { currency: "MUR", currencyName: "Mauritian Rupee", country: "Mauritius" },
  { currency: "MVR", currencyName: "Maldivian Rufiyaa", country: "Maldives" },
  { currency: "MWK", currencyName: "Malawian Kwacha", country: "Malawi" },
  { currency: "MXN", currencyName: "Mexican Peso", country: "Mexico" },
  { currency: "MYR", currencyName: "Malaysian Ringgit", country: "Malaysia" },
  {
    currency: "MZN",
    currencyName: "Mozambican Metical",
    country: "Mozambique",
  },
  { currency: "NAD", currencyName: "Namibian Dollar", country: "Namibia" },
  { currency: "NGN", currencyName: "Nigerian Naira", country: "Nigeria" },
  { currency: "NIO", currencyName: "Nicaraguan Córdoba", country: "Nicaragua" },
  { currency: "NOK", currencyName: "Norwegian Krone", country: "Norway" },
  { currency: "NPR", currencyName: "Nepalese Rupee", country: "Nepal" },
  {
    currency: "NZD",
    currencyName: "New Zealand Dollar",
    country: "New Zealand",
  },
  { currency: "OMR", currencyName: "Omani Rial", country: "Oman" },
  { currency: "PAB", currencyName: "Panamanian Balboa", country: "Panama" },
  { currency: "PEN", currencyName: "Peruvian Sol", country: "Peru" },
  {
    currency: "PGK",
    currencyName: "Papua New Guinean Kina",
    country: "Papua New Guinea",
  },
  { currency: "PHP", currencyName: "Philippine Peso", country: "Philippines" },
  { currency: "PKR", currencyName: "Pakistani Rupee", country: "Pakistan" },
  { currency: "PLN", currencyName: "Polish Złoty", country: "Poland" },
  { currency: "PYG", currencyName: "Paraguayan Guaraní", country: "Paraguay" },
  { currency: "QAR", currencyName: "Qatari Riyal", country: "Qatar" },
  { currency: "RON", currencyName: "Romanian Leu", country: "Romania" },
  { currency: "RSD", currencyName: "Serbian Dinar", country: "Serbia" },
  { currency: "RUB", currencyName: "Russian Ruble", country: "Russia" },
  { currency: "RWF", currencyName: "Rwandan Franc", country: "Rwanda" },
  { currency: "SAR", currencyName: "Saudi Riyal", country: "Saudi Arabia" },
  {
    currency: "SBD",
    currencyName: "Solomon Islands Dollar",
    country: "Solomon Islands",
  },
  { currency: "SCR", currencyName: "Seychellois Rupee", country: "Seychelles" },
  { currency: "SDG", currencyName: "Sudanese Pound", country: "Sudan" },
  { currency: "SEK", currencyName: "Swedish Krona", country: "Sweden" },
  { currency: "SGD", currencyName: "Singapore Dollar", country: "Singapore" },
  {
    currency: "SHP",
    currencyName: "Saint Helena Pound",
    country: "Saint Helena",
  },
  {
    currency: "SLE",
    currencyName: "Sierra Leonean Leone",
    country: "Sierra Leone",
  },
  { currency: "SOS", currencyName: "Somali Shilling", country: "Somalia" },
  { currency: "SRD", currencyName: "Surinamese Dollar", country: "Suriname" },
  {
    currency: "SSP",
    currencyName: "South Sudanese Pound",
    country: "South Sudan",
  },
  {
    currency: "STN",
    currencyName: "São Tomé and Príncipe Dobra",
    country: "São Tomé and Príncipe",
  },
  { currency: "SYP", currencyName: "Syrian Pound", country: "Syria" },
  { currency: "SZL", currencyName: "Eswatini Lilangeni", country: "Eswatini" },
  { currency: "THB", currencyName: "Thai Baht", country: "Thailand" },
  {
    currency: "TJS",
    currencyName: "Tajikistani Somoni",
    country: "Tajikistan",
  },
  {
    currency: "TMT",
    currencyName: "Turkmenistan Manat",
    country: "Turkmenistan",
  },
  { currency: "TND", currencyName: "Tunisian Dinar", country: "Tunisia" },
  { currency: "TOP", currencyName: "Tongan Paʻanga", country: "Tonga" },
  { currency: "TRY", currencyName: "Turkish Lira", country: "Turkey" },
  {
    currency: "TTD",
    currencyName: "Trinidad and Tobago Dollar",
    country: "Trinidad and Tobago",
  },
  { currency: "TVD", currencyName: "Tuvaluan Dollar", country: "Tuvalu" },
  { currency: "TWD", currencyName: "New Taiwan Dollar", country: "Taiwan" },
  { currency: "TZS", currencyName: "Tanzanian Shilling", country: "Tanzania" },
  { currency: "UAH", currencyName: "Ukrainian Hryvnia", country: "Ukraine" },
  { currency: "UGX", currencyName: "Ugandan Shilling", country: "Uganda" },
  {
    currency: "USD",
    currencyName: "United States Dollar",
    country: "United States",
  },
  { currency: "UYU", currencyName: "Uruguayan Peso", country: "Uruguay" },
  { currency: "UZS", currencyName: "Uzbekistani So'm", country: "Uzbekistan" },
  {
    currency: "VES",
    currencyName: "Venezuelan Bolívar Soberano",
    country: "Venezuela",
  },
  { currency: "VND", currencyName: "Vietnamese Đồng", country: "Vietnam" },
  { currency: "VUV", currencyName: "Vanuatu Vatu", country: "Vanuatu" },
  { currency: "WST", currencyName: "Samoan Tālā", country: "Samoa" },
  {
    currency: "XAF",
    currencyName: "Central African CFA Franc",
    country: "CEMAC",
  },
  {
    currency: "XCD",
    currencyName: "East Caribbean Dollar",
    country: "Organisation of Eastern Caribbean States",
  },
  {
    currency: "XDR",
    currencyName: "Special Drawing Rights",
    country: "International Monetary Fund",
  },
  { currency: "XOF", currencyName: "West African CFA franc", country: "CFA" },
  {
    currency: "XPF",
    currencyName: "CFP Franc",
    country: "Collectivités d'Outre-Mer",
  },
  { currency: "YER", currencyName: "Yemeni Rial", country: "Yemen" },
  {
    currency: "ZAR",
    currencyName: "South African Rand",
    country: "South Africa",
  },
  { currency: "ZMW", currencyName: "Zambian Kwacha", country: "Zambia" },
  { currency: "ZWL", currencyName: "Zimbabwean Dollar", country: "Zimbabwe" },
];
